# Navigation

nav:
  - PRF600 :
    - portraits_performa/index.md
    - Portrait 1: portraits_performa/premier_portrait.md
    - Portrait 2: portraits_performa/deuxieme_portrait.md
    - Portrait 3: portraits_performa/troisieme_portrait.md
  - PRF610 : 
    - prf610/index.md
    - TP1: prf610/travail1.md
  - PRF630 : 
    - prf630/index.md
  
  
 

###########################################################################
###########################################################################

# Theme (Material de Google) 
theme:
  name: material
  language: fr
  logo: _/logo-tim.svg
  favicon: _/favicon-32x32.png
  features:
    - content.tooltips
    - content.code.copy
    - toc.follow
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.path
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode clair
    - media: "(prefers-color-scheme: light)"
      primary: pink
      scheme: default
      toggle:
        icon: material/weather-night
        name: Mode sombre

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      options:
        emoji_index: twemoji
        emoji_generator: twemoji
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

    
# Extras
extra:
  generator: false

extra_css:
  - _/extra.css

extra_javascript:
  - _/extra.js

plugins:
  - offline
  - mkdocs-video

# Project information 
site_name: Travaux Performa
site_url:  https://flora0510.github.io/performa_portrait/
copyright: Lora Boisvert | Collège Montmorency
